# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structural_verification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dstructural_verification.proto\x12\x0esep.structural\"L\n\x11StructuralRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x12\n\ninput_type\x18\x02 \x01(\t\x12\x12\n\nbit_length\x18\x03 \x01(\r\"\x9b\x01\n\x12StructuralResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x0e\n\x06hazard\x18\x02 \x01(\x01\x12\x11\n\tcoherence\x18\x03 \x01(\x01\x12\x11\n\tstability\x18\x04 \x01(\x01\x12\x0f\n\x07\x65ntropy\x18\x05 \x01(\x01\x12\r\n\x05sig_c\x18\x06 \x01(\r\x12\r\n\x05sig_s\x18\x07 \x01(\r\x12\r\n\x05sig_e\x18\x08 \x01(\r2l\n\x12StructuralVerifier\x12V\n\x0bScoreWindow\x12!.sep.structural.StructuralRequest\x1a\".sep.structural.StructuralResponse\"\x00\x62\x06proto3')



_STRUCTURALREQUEST = DESCRIPTOR.message_types_by_name['StructuralRequest']
_STRUCTURALRESPONSE = DESCRIPTOR.message_types_by_name['StructuralResponse']
StructuralRequest = _reflection.GeneratedProtocolMessageType('StructuralRequest', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTURALREQUEST,
  '__module__' : 'structural_verification_pb2'
  # @@protoc_insertion_point(class_scope:sep.structural.StructuralRequest)
  })
_sym_db.RegisterMessage(StructuralRequest)

StructuralResponse = _reflection.GeneratedProtocolMessageType('StructuralResponse', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTURALRESPONSE,
  '__module__' : 'structural_verification_pb2'
  # @@protoc_insertion_point(class_scope:sep.structural.StructuralResponse)
  })
_sym_db.RegisterMessage(StructuralResponse)

_STRUCTURALVERIFIER = DESCRIPTOR.services_by_name['StructuralVerifier']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRUCTURALREQUEST._serialized_start=49
  _STRUCTURALREQUEST._serialized_end=125
  _STRUCTURALRESPONSE._serialized_start=128
  _STRUCTURALRESPONSE._serialized_end=283
  _STRUCTURALVERIFIER._serialized_start=285
  _STRUCTURALVERIFIER._serialized_end=393
# @@protoc_insertion_point(module_scope)
